import { Answer } from './types';
import { questions } from './questions';
import { sanitizeProjectName } from './sanitize';

interface SpecSection {
  title: string;
  content: string;
}

function getAnswerForSection(answers: Answer[], sectionNumber: number): string[] {
  const sectionQuestions = questions.filter((q) => q.sectionNumber === sectionNumber);
  const sectionAnswers: string[] = [];

  for (const q of sectionQuestions) {
    const answer = answers.find((a) => a.question === q.text);
    if (answer && answer.answer.trim()) {
      sectionAnswers.push(answer.answer);
    }
  }

  return sectionAnswers;
}

export function buildSpecFromAnswers(answers: Answer[]): string {
  const sections: SpecSection[] = [];

  // Section 1: Project Title (sanitized)
  const titleAnswers = getAnswerForSection(answers, 1);
  const projectTitle = sanitizeProjectName(titleAnswers[0] || 'Untitled Project');
  sections.push({
    title: '1. Project Title',
    content: `**${projectTitle}**`,
  });

  // Section 2: One-Paragraph Summary
  const summaryAnswers = getAnswerForSection(answers, 2);
  sections.push({
    title: '2. One-Paragraph Summary',
    content: summaryAnswers[0] || 'No summary provided.',
  });

  // Section 3: Primary Goal
  const goalAnswers = getAnswerForSection(answers, 3);
  sections.push({
    title: '3. Primary Goal',
    content: goalAnswers[0] || 'No primary goal defined.',
  });

  // Section 4: Constraints
  const constraintAnswers = getAnswerForSection(answers, 4);
  sections.push({
    title: '4. Constraints (Hard Rules)',
    content:
      constraintAnswers.length > 0
        ? 'These are **non-negotiable**.\n\n' + constraintAnswers.map((a) => `- ${a}`).join('\n')
        : 'No constraints defined.',
  });

  // Section 5: In-Scope Requirements
  const requirementAnswers = getAnswerForSection(answers, 5);
  sections.push({
    title: '5. In-Scope Requirements',
    content: requirementAnswers[0] || 'No requirements defined.',
  });

  // Section 6: Explicit Non-Goals
  const nonGoalAnswers = getAnswerForSection(answers, 6);
  sections.push({
    title: '6. Explicit Non-Goals (Critical)',
    content:
      nonGoalAnswers.length > 0
        ? 'What we are **not building**, even if it seems obvious:\n\n' + nonGoalAnswers[0]
        : 'No non-goals defined.',
  });

  // Section 7: Data Model
  const dataModelAnswers = getAnswerForSection(answers, 7);
  sections.push({
    title: '7. Data Model',
    content:
      dataModelAnswers.length > 0
        ? dataModelAnswers.join('\n\n### Relationships\n\n')
        : 'No data model defined.',
  });

  // Section 8: Interfaces
  const interfaceAnswers = getAnswerForSection(answers, 8);
  sections.push({
    title: '8. Interfaces',
    content:
      interfaceAnswers.length > 0
        ? '### User Flow\n\n' +
          interfaceAnswers[0] +
          (interfaceAnswers[1] ? '\n\n### APIs & Services\n\n' + interfaceAnswers[1] : '')
        : 'No interfaces defined.',
  });

  // Section 9: Execution Order
  const executionAnswers = getAnswerForSection(answers, 9);
  sections.push({
    title: '9. Execution Order (Recommended)',
    content: executionAnswers[0] || 'No build sequence defined.',
  });

  // Section 10: Success Criteria
  const successAnswers = getAnswerForSection(answers, 10);
  sections.push({
    title: '10. Success Criteria',
    content: successAnswers[0] || 'No success criteria defined.',
  });

  // Build final spec
  const header = `# Project Spec: ${titleAnswers[0] || 'Untitled Project'}

This spec was generated by SpecifyThat — turn a vague idea into a build-ready spec in under 60 seconds.

------------------------------------------------------------------------
`;

  const footer = `
------------------------------------------------------------------------

## Notes

Review each section and adjust as needed before implementation.

**Generated on**: ${new Date().toLocaleDateString()}
`;

  const body = sections
    .map((s) => `## ${s.title}\n\n${s.content}`)
    .join('\n\n------------------------------------------------------------------------\n\n');

  return header + body + footer;
}
