import { Answer } from './types';
import { questions } from './questions';
import { sanitizeProjectName } from './sanitize';

function getAnswerForSection(answers: Answer[], sectionNumber: number): string[] {
  const sectionQuestions = questions.filter((q) => q.sectionNumber === sectionNumber);
  const sectionAnswers: string[] = [];

  for (const q of sectionQuestions) {
    const answer = answers.find((a) => a.question === q.text);
    if (answer && answer.answer.trim()) {
      sectionAnswers.push(answer.answer);
    }
  }

  return sectionAnswers;
}

/**
 * Build a copilot-instructions.md file from the 13 interview answers.
 *
 * Output format matches the Modryn Studio boilerplate structure:
 * structured context that AI coding tools consume — not a traditional
 * spec or PRD.
 */
export function buildSpecFromAnswers(answers: Answer[]): string {
  const sections: string[] = [];

  // ─── Header ──────────────────────────────────────────────────
  const titleAnswers = getAnswerForSection(answers, 1);
  const projectName = sanitizeProjectName(titleAnswers[0] || 'Untitled Project');
  sections.push(`# ${projectName} — Copilot Context`);

  // ─── Product ─────────────────────────────────────────────────
  const summaryAnswers = getAnswerForSection(answers, 2);
  const goalAnswers = getAnswerForSection(answers, 3);
  const productLines: string[] = [];
  if (summaryAnswers[0]) productLines.push(summaryAnswers[0]);
  if (goalAnswers[0]) productLines.push(`\n**Primary goal:** ${goalAnswers[0]}`);
  sections.push(`## Product\n${productLines.join('\n') || 'No description provided.'}`);

  // ─── Stack & Constraints ─────────────────────────────────────
  const constraintAnswers = getAnswerForSection(answers, 4);
  const apiAnswers = getAnswerForSection(answers, 8); // section 8 = Interfaces (APIs)
  const stackLines: string[] = [];
  if (constraintAnswers.length > 0) {
    stackLines.push(...constraintAnswers);
  }
  // Pull API/service info from Q11 (sectionNumber 8, second question)
  const apiServiceAnswer = apiAnswers[1]; // Q11 is the second question in section 8
  if (apiServiceAnswer) {
    stackLines.push(`\n**External services:**\n${apiServiceAnswer}`);
  }
  if (stackLines.length > 0) {
    sections.push(`## Stack & Constraints\n${stackLines.join('\n')}`);
  }

  // ─── Core Features ──────────────────────────────────────────
  const requirementAnswers = getAnswerForSection(answers, 5);
  if (requirementAnswers[0]) {
    sections.push(`## Core Features (v1)\n${requirementAnswers[0]}`);
  }

  // ─── Non-Goals ───────────────────────────────────────────────
  const nonGoalAnswers = getAnswerForSection(answers, 6);
  if (nonGoalAnswers[0]) {
    sections.push(
      `## Non-Goals\nWhat we are **not** building right now, even if it seems obvious:\n\n${nonGoalAnswers[0]}`
    );
  }

  // ─── Data Model ──────────────────────────────────────────────
  const dataModelAnswers = getAnswerForSection(answers, 7);
  if (dataModelAnswers.length > 0) {
    const dataModelContent = dataModelAnswers[0] +
      (dataModelAnswers[1] ? `\n\n**Relationships:**\n${dataModelAnswers[1]}` : '');
    sections.push(`## Data Model\n${dataModelContent}`);
  }

  // ─── Route Map & User Flow ───────────────────────────────────
  const interfaceAnswers = getAnswerForSection(answers, 8);
  if (interfaceAnswers[0]) {
    sections.push(`## Route Map & User Flow\n${interfaceAnswers[0]}`);
  }

  // ─── Build Sequence ──────────────────────────────────────────
  const executionAnswers = getAnswerForSection(answers, 9);
  if (executionAnswers[0]) {
    sections.push(`## Build Sequence\n${executionAnswers[0]}`);
  }

  // ─── Success Criteria ────────────────────────────────────────
  const successAnswers = getAnswerForSection(answers, 10);
  if (successAnswers[0]) {
    sections.push(`## Success Criteria\n${successAnswers[0]}`);
  }

  // ─── Footer ──────────────────────────────────────────────────
  const filePath = '.github/copilot-instructions.md';
  sections.push(
    `---\n\n*Generated by [SpecifyThat](https://specifythat.com) on ${new Date().toLocaleDateString()}. ` +
    `Paste this file into your editor as \`${filePath}\` or add it to your AI tool's context.*`
  );

  return sections.join('\n\n');
}
